config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :edit, :create, :update, :show] do
    collection do
      get :existing_user
      post :sign_in
    end

    member do
      get :change_password
      post :submit_password
    end
  end

  root "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include BCrypt
  mount_uploader :profile_picture, ProfilePictureUploader
  has_secure_password
  validates :first_name, :last_name, :dob, :profile_picture, :email, presence: true
  validates :email, uniqueness: true

  def original_password
    byebug
    @original_password ||= Password.new(password_digest)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:edit, :update, :show, :change_password, :submit_password]

  # user/sign Up
  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User successfully signed up"
      redirect_to user_path(@user)
    else
      flash[:error] = "User registration failed with errors: #{@user.errors.full_messages.join(", ")}"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "User successfully Updated"
      redirect_to user_path(@user)
    else
      flash[:error] = "Failed with errors: #{@user.errors.full_messages.join(", ")}"
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def sign_in
    @user = User.where(email: params[:email]).first
    if @user && @user.authenticate(params[:password])
      redirect_to user_path(@user)
    else
      flash[:error] = "User Email/Password not matched"
      render :existing_user
    end
  end

  def existing_user
  end

  def change_password
  end

  def submit_password
    user = @user.authenticate(params[:current_password])
    if user
      user.update_attributes(password: params[:new_password])
      flash[:success] = "Password successfully Updated"
      redirect_to user_path(@user)
    else
      flash[:error] = "Password Update Failed!!/ Check the passwords you entered"
      redirect_to change_password_user_path(@user)
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :dob, :email, :profile_picture, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
        <div><%= value %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/change_password.html.erb
<div class="container">
  <h1> Change Your password </h1>

  <%= form_tag(submit_password_user_path(@user)) do %>
    <div>
      <%= label_tag "Current Password" %>
      <%= password_field_tag :current_password, "", required: true %>
    </div>
    <div>
      <%= label_tag "New Password" %>
      <%= password_field_tag :new_password, "", required: true %>
    </div>

    <div>
      <%= submit_tag "Update Password", class: "button" %>
      <%= link_to "Back", edit_user_path(@user), class: "button" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1> Edit Info </h1>

  <%= form_for @user, url: user_path(@user) do |f| %>
    <div>
      <%= f.label "First Name" %>
      <%= f.text_field :first_name, required: true %>
    </div>
    <div>
      <%= f.label "Last name" %>
      <%= f.text_field :last_name, required: true %>
    </div>
    <div>
      <%= f.label "DOB" %>
      <%= f.date_field :dob, required: true %>
    </div>
    <div>
      <%= f.label "Email" %>
      <%= f.email_field :email, required: true %>
    </div>
    <div>
      <%= f.label "Upload New Profile Picture" %>
      <%= f.file_field :profile_picture %>
      <%= image_tag(@user.profile_picture_url.to_s) %>
    </div>
    <div>
      <%= link_to "Change Password", change_password_user_path(@user), class: "button" %>
      <%= f.submit "Update", class: "button" %><br />
    </div>
    <div>
      <%= link_to "Back", user_path(@user), class: "button" %>
    </div>
  <% end %>
</div>

app/views/users/existing_user.html.erb
<div class="container">
  <h1> Sign In </h1>

  <%= form_tag(sign_in_users_path) do %>
    <div>
      <%= label_tag "Email" %>
      <%= email_field_tag :email, "", required: true %>
    </div>
    <div>
      <%= label_tag "Password" %>
      <%= password_field_tag :password, "", required: true %>
    </div>
    <div>
      <%= submit_tag "Sign In", class: "button" %>
      <%= link_to "Back", new_user_path, class: "button" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1> Sign Up </h1>
  <p> You already have an account? <strong><%= link_to "Sign In", existing_user_users_path %></strong> </p>
  <%= form_for @user, {url: users_path} do |f| %>
    <div>
      <%= f.label "First Name" %>
      <%= f.text_field :first_name, required: true %>
    </div>
    <div>
      <%= f.label "Last name" %>
      <%= f.text_field :last_name, required: true %>
    </div>
    <div>
      <%= f.label "DOB" %>
      <%= f.date_field :dob, required: true %>
    </div>
    <div>
      <%= f.label "Email" %>
      <%= f.email_field :email, required: true %>
    </div>
    <div>
      <%= f.label "Upload Profile Picture" %>
      <%= f.file_field :profile_picture, required: true %>
    </div>
    <div>
      <%= f.label "Password" %>
      <%= f.password_field :password, required: true %>
    </div>
    <div>
      <%= f.submit "Sign Up", class: "button" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1> Personal Information </h1>
  <p>Full name: <strong><%= @user.first_name + " " + @user.last_name %></strong> </p> 
  <%= image_tag(@user.profile_picture_url.to_s) %>
  <p>Email: <strong><%= @user.email %></strong></p>
  <p>DOB: <strong><%= @user.dob %></strong></p>

  <%= link_to "Update Information", edit_user_path(@user), class: "button" %>
  <%= link_to "Sign Out", new_user_path, class: "button" %>
</div>